### ISSUE TITLE
Error when Switching to Goerli Network: Removed Sepolia Network Configurations

### ISSUE THREAD

**Issue by Merlin2100** [Merlin2100/my-dex#2]
I have removed/commented out The Sepolia network configurations in the following files:

- hardhat.config.js
- config.json
- Navbar.js- 

However, when I switch to the Goerli network and perform the following steps:

1. Open the MetaMask popup and click on the 'Switch network' button.
2. Click on the 'Connect' button on the 'My Token Exchange' website.
==> I encounter an error. Please refer to the attached screenshot for details.
![2023-12-14 error by clicking connect](https://github.com/Merlin2100/my-dex/assets/139470242/fd7003c6-317d-4a6b-925e-cf6663ce9507)

**Comment by lyrx** [comment]
First we have to get the tests clean with 0 errors. Does it work for you, Karsten? I fixed one simple error in my branch, but there is one error still present in the tests: `npx hardhat test`

**Comment by Merlin2100** [comment]
All tests have now passed

**Comment by lyrx** [comment]
Seems to work on my branch. Did not check the master branch yet. You still have problems?

**Comment by lyrx** [comment]
Take this: https://github.com/Merlin2100/my-dex/blob/alex/src/store/interactions.js#L12

**Comment by lyrx** [comment]
Did you change the default branch? What is 'alt-history' ?

**Comment by Merlin2100** [comment]
> Seems to work on my branch. Did not check the master branch yet. You still have problems?

> Did you change the default branch? What is 'alt-history' ?

The problems shown all relate to the 
[alt-history](https://github.com/Merlin2100/my-dex/tree/alt-history) (default) branch, where I implement. On this branch:

Everything passed the test `npx hardhat test`.
I encounter an error (Issue #2) when I switch to the Sepolia network.
This is the current state (Branch: [alt-history](https://github.com/Merlin2100/my-dex/tree/alt-history) - Default).

**Comment by Merlin2100** [comment]
> Take this: https://github.com/Merlin2100/my-dex/blob/alex/src/store/interactions.js#L12

I have adjusted what you mentioned locally, but I still encounter the same error (Issue #2) when I connect to the Goerli network.

**Comment by lyrx** [comment]
Ok, let's do it step by step. I am on the alt-history branch now. First you lost one of the test fixes again. So `npx hardhat test` gives an error. It will be simple to fix.  The second reason that `npx hardhat test` gives errors is because somebody who checks out your project does not necessarily have private keys prepared to use for the testnets. So you need to change hardhat.config.js in such a way, that it works without the testnets. Maybe just use your own hardhat.config.js locally and push another one that can be used as is without additional configurations. When `npx hardhat` test works, we can move on ...

**Comment by Merlin2100** [comment]
It looks like there's an issue with the [**PriceChart.js**](https://github.com/Merlin2100/my-dex/blob/2341f55dfadce2e4b6321c21c88319ca188a8ee7/src/components/PriceChart.js#L42C1-L52C11) section. When I commented out that part, the network connection (Goerli/Hardhat) continued without any errors. This hints at a possible problem within the code or functionality of the [**PriceChart.js**](https://github.com/Merlin2100/my-dex/blob/2341f55dfadce2e4b6321c21c88319ca188a8ee7/src/components/PriceChart.js#L42C1-L52C11). To figure out what's going on, I'll need to check for errors, misconfigurations, or other factors that might be causing the problem. What potential issues should I look into here?"

**Comment by lyrx** [comment]
I will look into it tomorrow. Most likely it is because of your changes in config.json. You only need to remove the testnets in the hardhat config file.

**Comment by marcobesier** [comment]
@lyrx I think it's fine if @Merlin2100 leaves his hardhat.config.js as is for now. I mean, we can simply comment it out on our side, right? 🙂 Clearly, this is something that would need to change if he wants to share the repo "at scale" but for now, this is fine imo. Feel free to prove me wrong, though!

**Comment by marcobesier** [comment]
@Merlin2100 Given that the original error tells you that you're "reading '0' from undefined" and given that you don't encounter the issue when you're leaving out the PriceChart component, it smells like there could be an issue with the `symbols` variable. Can you please `console.log(symbols)` after the line `const symbols = useSelector(state => state.tokens.symbols)`? Does this give you `undefined` or does it just log the symbols array as expected?

I would do it myself, but for whatever reason Hardhat refuses to download the Solidity compiler, which prevents me from doing anything atm. -.- Restarted my machine, double-checked my internet connection, nuked and paved the project, etc. Nothing seems to help atm. Really weird given that I ran the same repo just 2 days ago and it worked just fine... Anyway...

I'll try my best to get it running asap.

In the meanwhile, out of curiosity: Can you clone the following repo

https://github.com/marcobesier/my-dex.git

and complete the last two lessons based on this repo? Note that you need to add the copy of your current .env file manually to this repo so that it knows your private keys.

**Comment by lyrx** [comment]
The 'alex' branch should work now. There is just one hardhat test error that needs to be fixed. Secondly, I did not manually test the complete application, just the startup, and that works for Sepolia, Goerli and the local hardhat node. So what remains to be done is testing the app and fixing the hardhat test. You will see what I fixed if you compare the 'alex' branch with 'alt-history'.

**Comment by marcobesier** [comment]
Which test is failing specifically? Would you mind sharing a screenshot? 🙂

**Comment by lyrx** [comment]
I just fixed the test in the 'alex' branch by taking over Karsten's changes on 'alt-history'.  My impression at the moment is that Karsten is very close to the finishing line. There seems to be not much missing. The only error I found so far, I fixed in the 'alex' branch.  One last tipp: I don't think 'removing' networks or testing on different networks really helps. There is not much wrong. Everything works on the hardhat network and on the test networks, as far as I tested it.

**Comment by marcobesier** [comment]
@Merlin2100 Is the issue resolved on your end, too? Please let me know if that's not the case yet.

**Comment by Merlin2100** [comment]
> @Merlin2100 Given that the original error tells you that you're "reading '0' from undefined" and given that you don't encounter the issue when you're leaving out the PriceChart component, it smells like there could be an issue with the `symbols` variable. Can you please `console.log(symbols)` after the line `const symbols = useSelector(state => state.tokens.symbols)`? Does this give you `undefined` or does it just log the symbols array as expected?

@marcobesier 
Yes, the system does log the symbols array as expected.


> @Merlin2100 Is the issue resolved on your end, too? Please let me know if that's not the case yet.

@marcobesier Problem persists on my end

**Comment by lyrx** [comment]
How can I reproduce the problem on the default branch?

**Comment by marcobesier** [comment]
@Merlin2100 Dang... How about cloning my my-dex repo? Any chance that worked out without issues?

**Comment by Merlin2100** [comment]
## Short applause for the troops! 🚀

Hi @lyrx & @marcobesier 

thank you for your tireless support with this problem.
Thanks for the great teamwork! I really appreciate it!

By the way, good news – it works now! 🎉 I copied some files again:

1. Copied some files, and, voila, problem solved!
2. Uninstalled three pesky entries from `package.json` using 'npx uninstall ...':
    - @babel/plugin-proposal-private-property-in-object
    - cross-env
    - open-cli
3. Also, copied the `package-lock.json` file entirely from Zhana's repository.

Appreciate it!

Cheers

**Comment by lyrx** [comment]
Congratulations Karsten!! One last remark. One last remark: It would really be benificial to understand what the problem really was. So I looked at the changes you made. You corrected a typo in Alert.js . I suggest you revert that and check if the error re-occurs. If it re-occurs and goes away again after re-correcting the typo again, you might know what was behind your problem. The other changes you made, I am not sure if they are related to the problem.

**Comment by marcobesier** [comment]
Congrats, Karsten! Great job! 👏 🥳 

I agree with Alex: It would be insightful to pin down the issue to a specific change of yours to understand what the problem was. So, definitely give this a shot. 🙂

But again: First and foremost, congratulations on wrapping up this project! You've come a long way!

Time to tackle your advanced ERC-20 project now. 😎

**Comment by Merlin2100** [comment]
Thanks for the congratulations! I retested the typo in Alert.js, and switching/connecting between networks works perfectly.
I'll keep an eye on it and now proceed to deploy the frontend. 🚀
